export const personas = [
  {
    id: 1,
    nombre: "Nikolia",
    email: "ngatty0@webs.com",
    genero: "Female",
    edad: 52,
  },
  {
    id: 2,
    nombre: "Lewie",
    email: "llynthal1@devhub.com",
    genero: "Male",
    edad: 46,
  },
  {
    id: 3,
    nombre: "Lexi",
    email: "lglede2@networksolutions.com",
    genero: "Bigender",
    edad: 21,
  },
  {
    id: 4,
    nombre: "Westbrooke",
    email: "wbatter3@unesco.org",
    genero: "Male",
    edad: 26,
  },
  {
    id: 5,
    nombre: "Elie",
    email: "egervaise4@comcast.net",
    genero: "Female",
    edad: 26,
  },
  {
    id: 6,
    nombre: "Perrine",
    email: "pproffitt5@mapy.cz",
    genero: "Non-binary",
    edad: 39,
  },
  {
    id: 7,
    nombre: "Julee",
    email: "jblankman6@list-manage.com",
    genero: "Female",
    edad: 35,
  },
  {
    id: 8,
    nombre: "Reese",
    email: "ryersin7@delicious.com",
    genero: "Male",
    edad: 34,
  },
  {
    id: 9,
    nombre: "Chad",
    email: "ccattermole8@fotki.com",
    genero: "Male",
    edad: 48,
  },
  {
    id: 10,
    nombre: "Pinchas",
    email: "pboyland9@unesco.org",
    genero: "Male",
    edad: 31,
  },
  {
    id: 11,
    nombre: "Papageno",
    email: "pbranchetta@g.co",
    genero: "Male",
    edad: 32,
  },
  {
    id: 12,
    nombre: "Javier",
    email: "jgullandb@nhs.uk",
    genero: "Male",
    edad: 64,
  },
  {
    id: 13,
    nombre: "Ignacio",
    email: "itroughtonc@scribd.com",
    genero: "Male",
    edad: 53,
  },
  {
    id: 14,
    nombre: "Vinnie",
    email: "vmaccrossand@time.com",
    genero: "Agender",
    edad: 43,
  },
  {
    id: 15,
    nombre: "Kip",
    email: "kverdune@simplemachines.org",
    genero: "Female",
    edad: 42,
  },
  {
    id: 16,
    nombre: "Julian",
    email: "jwithersf@washingtonpost.com",
    genero: "Male",
    edad: 42,
  },
  {
    id: 17,
    nombre: "Zolly",
    email: "zvanderlindeg@jugem.jp",
    genero: "Male",
    edad: 51,
  },
  {
    id: 18,
    nombre: "Meta",
    email: "mducharth@wix.com",
    genero: "Female",
    edad: 43,
  },
  {
    id: 19,
    nombre: "Grove",
    email: "gwoodburnei@bizjournals.com",
    genero: "Male",
    edad: 44,
  },
  {
    id: 20,
    nombre: "Dorena",
    email: "dkrzyzowskij@sciencedaily.com",
    genero: "Female",
    edad: 28,
  },
  {
    id: 21,
    nombre: "Randene",
    email: "rfairbardk@stanford.edu",
    genero: "Non-binary",
    edad: 28,
  },
  {
    id: 22,
    nombre: "Fidel",
    email: "fextilll@census.gov",
    genero: "Male",
    edad: 47,
  },
  {
    id: 23,
    nombre: "Gearard",
    email: "gclaybornm@ifeng.com",
    genero: "Male",
    edad: 34,
  },
  {
    id: 24,
    nombre: "Helyn",
    email: "hgalian@howstuffworks.com",
    genero: "Female",
    edad: 62,
  },
  {
    id: 25,
    nombre: "Brocky",
    email: "bbuddleigho@nyu.edu",
    genero: "Male",
    edad: 58,
  },
  {
    id: 26,
    nombre: "Sammy",
    email: "sfrancklynp@freewebs.com",
    genero: "Male",
    edad: 22,
  },
  {
    id: 27,
    nombre: "Bartholemy",
    email: "besslementq@goo.gl",
    genero: "Male",
    edad: 34,
  },
  {
    id: 28,
    nombre: "Brady",
    email: "bbrimmellr@huffingtonpost.com",
    genero: "Male",
    edad: 36,
  },
  {
    id: 29,
    nombre: "Damita",
    email: "dsisses@newsvine.com",
    genero: "Agender",
    edad: 28,
  },
  {
    id: 30,
    nombre: "Darwin",
    email: "dingreet@businessinsider.com",
    genero: "Genderfluid",
    edad: 18,
  },
];

export function Persona(id, nombre,edad,email,genero){
  
  this.id=id;
  this.nombre=nombre;
  this.edad=edad;
  this.email=email;
  this.genero=genero;
}
