export const movies =[
            {"id":1,"movie_name":"Consequences of Love, The (Conseguenze dell'amore, Le)"},
            {"id":2,"movie_name":"Stranger in the House"},
            {"id":3,"movie_name":"Oscar and Lucinda (a.k.a. Oscar & Lucinda)"},
            {"id":4,"movie_name":"Cat Ballou"},
            {"id":5,"movie_name":"Somebody is Waiting"},
            {"id":6,"movie_name":"Bigfoot"},
            {"id":7,"movie_name":"Catch and Release"},
            {"id":8,"movie_name":"Against All Flags"},
            {"id":9,"movie_name":"Salvage"},
            {"id":10,"movie_name":"Viimeiset rotannahat "},
            {"id":11,"movie_name":"3 Little Ninjas and the Lost Treasure"},
            {"id":12,"movie_name":"The Land Unknown"},
            {"id":13,"movie_name":"River, The"},
            {"id":14,"movie_name":"What Price Hollywood?"},
            {"id":15,"movie_name":"Garlic Is As Good As Ten Mothers"},
            {"id":16,"movie_name":"Dad Savage"},
            {"id":17,"movie_name":"Delirious"},
            {"id":18,"movie_name":"Spy Kids 3-D: Game Over"},
            {"id":19,"movie_name":"Into the Woods"},
            {"id":20,"movie_name":"Lawless Range"},
            {"id":21,"movie_name":"Poltergeist III"},
            {"id":22,"movie_name":"Canyons, The"},
            {"id":23,"movie_name":"Superman/Doomsday "},
            {"id":24,"movie_name":"I giorni contati"},
            {"id":25,"movie_name":"Friendly Persuasion"},
            {"id":26,"movie_name":"Sandra of a Thousand Delights (Vaghe stelle dell'Orsa...)"},
            {"id":27,"movie_name":"Flowers in the Attic"},
            {"id":28,"movie_name":"Stacy"},
            {"id":29,"movie_name":"Patrik Age 1.5 (Patrik 1,5)"},
            {"id":30,"movie_name":"Bridge of Dragons"},
            {"id":31,"movie_name":"Bell Boy, The"},
            {"id":32,"movie_name":"Hangover Part II, The"},
            {"id":33,"movie_name":"Bug"},
            {"id":34,"movie_name":"Heartbeats (Kohtaamisia)"},
            {"id":35,"movie_name":"Young Gods (Hymypoika)"},
            {"id":36,"movie_name":"Piggy"},
            {"id":37,"movie_name":"Tokyo Joe"},
            {"id":38,"movie_name":"Queen: Days of Our Lives"},
            {"id":39,"movie_name":"Make Them Die Slowly (Cannibal Ferox)"},
            {"id":40,"movie_name":"There Be Dragons"},
            {"id":41,"movie_name":"Conscientious Objector, The"},
            {"id":42,"movie_name":"Double Life of Veronique, The (Double Vie de Véronique, La)"},
            {"id":43,"movie_name":"Kaksi kotia (Dagmamman)"},
            {"id":44,"movie_name":"Empty Nest (El nido vacío)"},
            {"id":45,"movie_name":"Sweet November"},
            {"id":46,"movie_name":"And Then There Were None"},
            {"id":47,"movie_name":"Tron"},
            {"id":48,"movie_name":"Awesome; I Fuckin Shot That!"},
            {"id":49,"movie_name":"Repo Man"},
            {"id":50,"movie_name":"Dark Eyes (Oci ciornie)"}];
